version: '3.7'
services:
  mixer-frontend:
    container_name: mixer-frontend

    build:
      context: ../frontend

    ports:
      - "1235:8001"

    networks:
      - "mixer-net"

    environment:
      - NODE_ENV=docker

networks:
  mixer-net:
