---
env: 'local-dev'

network:
    ganache:
        url: "http://localhost:8545"
        chainId: 1234
        supportedNetwork: 1234
        privateKeysPath: "../ganachePrivateKeys.json"
        supportedNetworkName: "Ganache"
        gasPrice: 20000000000
        token:
            eth:
                mixAmt: 0.1
                feeAmt: 0.001
                sym: 'ETH'
            tkn:
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'TKN'
        testing:
          privKeys:
            - "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3"
            - "0xae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f"
    kovan:
        url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
        chainId: 42
        supportedNetwork: 42
        privateKeysPath: "../kovanPrivateKeys.json"
        supportedNetworkName: "Kovan"
        blockExplorerTxPrefix: "https://kovan.etherscan.io/tx/"
        gasPrice: 20000000000
        hotWalletPrivKeyPath: "/home/mixer/key/hotWalletPrivKey.json"
        relayerAddress: "0xf17f52151EbEF6C7334FAD080c5704D77216b732"
        token:
            eth:
                mixAmt: 0.1
                feeAmt: 0.001
                sym: 'ETH'
            dai:
                deployedAddresse: '0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa'
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'DAI'
        testing:
          privKeys:
            - "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3"
            - "0xae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f"
    arbitrum:
        disable: true
        url: "https://kovan3.arbitrum.io/rpc"
        chainId: 79377087078960
        supportedNetwork: 79377087078960
        privateKeysPath: "../kovanPrivateKeys.json"
        blockExplorerTxPrefix: https://explorer.arbitrum.io/#/
        supportedNetworkName: "Arbitrum"
        gasPrice: 20000000000
        hotWalletPrivKeyPath: "/home/mixer/key/hotWalletPrivKey.json"
        relayerAddress: "0xf17f52151EbEF6C7334FAD080c5704D77216b732"
        token:
            eth:
                mixAmt: 0.1
                feeAmt: 0.001
                sym: 'ETH'
            tkn:
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'TKN'

network-test:
    ganache:
        disable: true
        url: "http://localhost:8545"
        chainId: 1234
        supportedNetwork: 1234
        privateKeysPath: "../ganachePrivateKeys.json"
        supportedNetworkName: "Ganache"
        gasPrice: 20000000000
        token:
            eth:
                mixAmt: 0.1
                feeAmt: 0.001
                sym: 'ETH'
            tkn:
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'TKN'
        testing:
          privKeys:
            - "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3"
            - "0xae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f"
    kovan:
        disable: true
        url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
        chainId: 42
        supportedNetwork: 42
        privateKeysPath: "../kovanPrivateKeys.json"
        supportedNetworkName: "Kovan"
        blockExplorerTxPrefix: "https://kovan.etherscan.io/tx/"
        gasPrice: 20000000000
        hotWalletPrivKeyPath: "/home/mixer/key/hotWalletPrivKey.json"
        relayerAddress: "0xf17f52151EbEF6C7334FAD080c5704D77216b732"
        token:
            eth:
                mixAmt: 0.1
                feeAmt: 0.001
                sym: 'ETH'
            tkn:
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'TKN'
        testing:
          privKeys:
            - "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3"
            - "0xae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f"
    arbitrum:
        url: "https://kovan3.arbitrum.io/rpc"
        chainId: 79377087078960
        supportedNetwork: 79377087078960
        privateKeysPath: "../kovanPrivateKeys.json"
        blockExplorerTxPrefix: "https://explorer.arbitrum.io/#/"
        supportedNetworkName: "Arbitrum"
        gasPrice: 20000000000
        hotWalletPrivKeyPath: "/home/mixer/key/hotWalletPrivKey.json"
        relayerAddress: "0xf17f52151EbEF6C7334FAD080c5704D77216b732"
        token:
            eth:
                mixAmt: 0.1
                feeAmt: 0.001
                sym: 'ETH'
            tkn:
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'TKN'

chain:
    gasLimit:
        mix: 8000000

backend:
  port: 3000
  host: "http://localhost"
  etcd:
    host: "localhost"
    port: 2379
    lockTime: 7000

frontend:
  snarks:
    paths:
      verificationKey: 'http://localhost:8000/build/verification_key.json'
      circuit: 'http://localhost:8000/build/circuit.json'
      provingKey: 'http://localhost:8000/build/proving_key.bin'
  countdown:
    endsAtUtcMidnight: false
    endsAfterSecs: 5
