---
env: 'local-dev'

network:

    kovan:
        disable: true
        useRegistry: true
        url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
        chainId: 42
        supportedNetwork: 42
        privateKeysPath: "kovanPrivateKeys.json"
        supportedNetworkName: "Kovan"
        blockExplorerTxPrefix: "https://kovan.etherscan.io/tx/"
        token:
            eth:
                mixAmt: 0.1
                feeAmt: 0.002
                surrogethFeeAmt: 0.001
                sym: 'KETH'
                name: 'Kovan Ether'
            tkn:
                address: "0x6fB66Fe3a00aFF2fD0a373223592D9Ebe21913eF"
                decimals: 18
                mixAmt: 100
                feeAmt: 2
                sym: 'TKN'
                name: 'Token'
            dai:
                address: '0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa'
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'DAI'
                name: 'Dai'

    ganache:
        disable: false
        useRegistry: true
        url: "http://localhost:8545"
        chainId: 1337
        supportedNetwork: 1337
        privateKeysPath: "ganachePrivateKeys.json"
        supportedNetworkName: "Ganache"
        token:
            eth:
                mixAmt: 0.102
                feeAmt: 0.002
                surrogethFeeAmt: 0.001
                sym: 'ETH'
                name: 'Ether'
            tkn:
                decimals: 18
                mixAmt: 102
                feeAmt: 2
                sym: 'TKN'
                name: 'Token'

    ganache2:
        disable: true
        useRegistry: false
        url: "http://localhost:8545"
        chainId: 1337
        supportedNetwork: 1337
        privateKeysPath: "ganachePrivateKeys.json"
        supportedNetworkName: "Ganache"
        token:
            eth:
                mixAmt: 0.1
                feeAmt: 0.002
                surrogethFeeAmt: 0.001
                sym: 'ETH'
                name: 'Ether'
            tkn:
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'TKN'
                name: 'Token'

    ropsten:
        disable: true
        useRegistry: true
        url: "https://ropsten.infura.io/v3/5d37c494621a43558d77c90e368d4022"
        chainId: 3
        supportedNetwork: 3
        privateKeysPath: "kovanPrivateKeys.json"
        supportedNetworkName: "Ropsten"
        blockExplorerTxPrefix: "https://ropsten.etherscan.io/tx/"
        token:
            eth:
                mixAmt: 0.1
                feeAmt: 0.002
                surrogethFeeAmt: 0.001
                sym: 'ETH'
            tkn:
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'TKN'
                name: 'Token'


    arbitrum:
        disable: true
        useRegistry: true
        url: "https://kovan3.arbitrum.io/rpc"
        chainId: 79377087078960
        supportedNetwork: 79377087078960
        privateKeysPath: "kovanPrivateKeys.json"
        blockExplorerTxPrefix: https://explorer.arbitrum.io/#/tx/
        supportedNetworkName: "Arbitrum"
        token:
            tkn:
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'TKN'
                name: 'Token'
            eth:
                mixAmt: 0.1
                feeAmt: 0.002
                surrogethFeeAmt: 0.001
                sym: 'ETH'
                name: 'Ether'
    skale:
        disable: true
        useRegistry: true
        url: "https://dev-testnet-v1-0.skalelabs.com"
        chainId: 344435
        supportedNetwork: 344435
        privateKeysPath: "kovanPrivateKeys.json"
        supportedNetworkName: "Skale"
        token:
            tkn:
                decimals: 18
                mixAmt: 20
                feeAmt: 0.02
                sym: 'TKN'
                name: 'Token'
            eth:
                mixAmt: 0.1
                feeAmt: 0.002
                surrogethFeeAmt: 0.001
                sym: 'ETH'
                name: 'Ether'

chain:
    gasLimit:
        mix: 8000000

backend:
  port: 3000
  host: "http://localhost"
  etcd:
    host: "localhost"
    port: 2379
    lockTime: 7000

frontend:
  snarks:
    paths:
      verificationKey: 'http://localhost:1234/build/verification_key.json'
      circuit: 'http://localhost:1234/build/circuit.json'
      provingKey: 'http://localhost:1234/build/proving_key.bin'
  countdown:
    endsAtUtcMidnight: false
    endsAfterSecs: 5

#for surrogeth compatibility
surrogethPort: 8124
surrogethIp: "127.0.0.1"
